name: sort_dependency_lists_lint
description: A custom lint for dart/flutter projects, that wants you to sort your dependency declarations
version: 1.0.0

environment:
  sdk: ^3.3.4

# Add regular dependencies here.
dependencies:
  analyzer: ^5.0.0
  analyzer_plugin: ^0.11.2
  custom_lint_builder: ^0.5.14
  path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
